# GitHub Actions workflow: build PyInstaller exe using spec and publish to GitHub Releases
# Trigger on version tags like v1.2.3
# Uses softprops/action-gh-release to handle release creation and asset upload in one step
actions:
  permissions:
    contents: write  # allow creating releases

name: Build and Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller using spec
        run: |
          pyinstaller Tasker.spec

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/Tasker.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
