# GitHub Actions workflow: build PyInstaller exe on manual release and upload to that GitHub Release
# Trigger when you publish (or republish) a Release via the GitHub UI
name: Build and Upload Release Asset

# Grant write access to release assets
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller using spec
        run: pyinstaller Tasker.spec

      - name: Upload executable asset to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Points to the tag you set when creating the Release in the UI
          tag_name: ${{ github.event.release.tag_name }}
          # Upload the built exe into that Release
          files: dist/Tasker.exe
          name: Tasker-${{ github.event.release.tag_name }}.exe
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
